// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtuRr-HnDuRp8pXvFd8rtpcV5qbKHg47k',
    appId: '1:318381496344:web:24b0784571d95e92698b6d',
    messagingSenderId: '318381496344',
    projectId: 'emtelek-a1c36',
    authDomain: 'emtelek-a1c36.firebaseapp.com',
    storageBucket: 'emtelek-a1c36.firebasestorage.app',
    measurementId: 'G-CFY6WTQ9G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyPJJbw4FCqLzbQWCyC6j0gdqrST23Gs4',
    appId: '1:318381496344:android:94ac3a54916058d5698b6d',
    messagingSenderId: '318381496344',
    projectId: 'emtelek-a1c36',
    storageBucket: 'emtelek-a1c36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf4EiavBSkFozUVsG-37BVq01OzI8vSoo',
    appId: '1:318381496344:ios:1e788799a4e18197698b6d',
    messagingSenderId: '318381496344',
    projectId: 'emtelek-a1c36',
    storageBucket: 'emtelek-a1c36.firebasestorage.app',
    iosBundleId: 'com.emtelektech.emtelek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf4EiavBSkFozUVsG-37BVq01OzI8vSoo',
    appId: '1:318381496344:ios:e14c3b3a2a9d098a698b6d',
    messagingSenderId: '318381496344',
    projectId: 'emtelek-a1c36',
    storageBucket: 'emtelek-a1c36.firebasestorage.app',
    iosBundleId: 'com.example.emtelek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtuRr-HnDuRp8pXvFd8rtpcV5qbKHg47k',
    appId: '1:318381496344:web:8568075e55af4fa0698b6d',
    messagingSenderId: '318381496344',
    projectId: 'emtelek-a1c36',
    authDomain: 'emtelek-a1c36.firebaseapp.com',
    storageBucket: 'emtelek-a1c36.firebasestorage.app',
    measurementId: 'G-RZ8FK3LJJG',
  );
}
